version: '3'

networks:
  proxy:
    external: true
services:

  ghost:
    container_name: sussike
    image: ghost:latest
    environment:
      - url=https://sussike.ee
    volumes:
      - /home/wauhost/src/apps/sussike-ee/data:/var/lib/ghost/content
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.sussike-secured.rule=Host(`sussike.ee`,`www.sussike.ee`)"
      - "traefik.http.routers.sussike-secured.entrypoints=websecure"
    networks:
      - proxy